server:
  port: 8081

spring:
  application:
    name: springboot_excel
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sql_test?useUnicode=true&characterEncoding=utf8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
logback:
  level:
    root: ERROR # ALL>TRACE>FATAL>DEBUG>INFO>WARN>ERROR>OFF
    file:
      max-history: 7 # 日志保存最长时间
      max-size: 10KB # 单个日志文件大小
      total-size-cap: 100KB # 日志文件总大小
      path: ./log
filePath: /accessory/